### PR TITLE
Fixes using label placeholder in validation rule with Html label

### LINKED ISSUE #234: Using Nette\Utils\Html as label with validation causes: rtrim() expects parameter 1 to be string, object given
Version: 3.0.1

### Bug Description
When using `Nette\Utils\Html` as caption/label for input, it will fail on TypeError in validator. This code worked in 2.4

Screenshot 2019-11-18 10 45 57

### Steps To Reproduce
```
$label = \Nette\Utils\Html::el()->setHtml('<i>Demo</i>');
        
$form->addText('demo', $label)
    ->setRequired('Please fill in %label.');
```

### Expected Behavior
To not throw exception and return `(string) $html` in `%label` placeholder.

### Possible Solution
This fix worked for us:

```diff
+                   $caption = $rule->control->getCaption();
                    return $rule->control instanceof Controls\BaseControl
-                        ? rtrim($rule->control->translate($rule->control->getCaption()), ':')
+                        ? $caption instanceof Nette\Utils\Html ? $caption : rtrim($rule->control->translate($caption), ':')
                        : null;
```

### PR DESCRIPTION
**Pull request by JanMikes**
Fixes #234

### CODE REVIEW

File: src/Forms/Validator.php [hunk 1]
```diff
@@ -69,9 +70,14 @@ public static function formatMessage(Rule $rule, bool $withValue = true)
 			static $i = -1;
 			switch ($m[1]) {
 				case 'name': return $rule->control->getName();
-				case 'label': return $rule->control instanceof Controls\BaseControl
-					? rtrim($rule->control->translate($rule->control->getCaption()), ':')
-					: null;
+				case 'label':
+					if ($rule->control instanceof Controls\BaseControl) {
```
Comment (JanMikes) [inline src/Forms/Validator.php]: I think this way (replacing ternary operator with if with early return)  is more readable intead of having 2 nested ternary operators, but i am opened to adapt it to desired codestyle needs - there is missing some coding standard tool to force code style :-).

**Comment by dg** [comment]
Thanks
